/* Generated By:JJTree: Do not edit this line. ASTAddMnsOp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.begic.interpreter.parser;

public
class ASTAddMnsOp extends SimpleNode {
  public ASTAddMnsOp(int id) {
    super(id);
  }

  public ASTAddMnsOp(BegicParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BegicParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bda78a6dbb34b2419abe8c3577e2cea6 (do not edit this line) */
