/* Generated By:JJTree: Do not edit this line. ASTConstantAssignment.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.begic.interpreter.parser;

public
class ASTConstantAssignment extends SimpleNode {
  public ASTConstantAssignment(int id) {
    super(id);
  }

  public ASTConstantAssignment(BegicParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BegicParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=52d90761d0e79c1fb666cb2bd41bdeac (do not edit this line) */
