/* Generated By:JJTree: Do not edit this line. ASTListHashFactor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.tolz.begic.prototype.interpreter.parser;

public
class ASTListHashFactor extends SimpleNode {
  public ASTListHashFactor(int id) {
    super(id);
  }

  public ASTListHashFactor(BegicParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BegicParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=170d9b8cab86e3d78be0d18fbe4e2ded (do not edit this line) */
