/* Generated By:JJTree: Do not edit this line. ASTSingleAddMnsOp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package jp.tolz.begic.prototype.interpreter.parser;

public
class ASTSingleAddMnsOp extends SimpleNode {
  public ASTSingleAddMnsOp(int id) {
    super(id);
  }

  public ASTSingleAddMnsOp(BegicParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BegicParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=46b31fa7c3d8d30d9c8fedfd7cc561fe (do not edit this line) */
