/* Generated By:JavaCC: Do not edit this line. BegicParserTreeConstants.java Version 6.0_1 */
package jp.tolz.begic.prototype.interpreter.parser;

public interface BegicParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCOMMAND = 1;
  public int JJTARGS = 2;
  public int JJTCALL = 3;
  public int JJTIFSTATEMENT = 4;
  public int JJTLOOPSTATEMENT = 5;
  public int JJTWHILESTATEMENT = 6;
  public int JJTFORSTATEMENT = 7;
  public int JJTBLOCK = 8;
  public int JJTBREAK = 9;
  public int JJTNEXT = 10;
  public int JJTASSINGMENT = 11;
  public int JJTOPERATION = 12;
  public int JJTOROP = 13;
  public int JJTANDOP = 14;
  public int JJTNOTOP = 15;
  public int JJTCOMPOP = 16;
  public int JJTCOMP = 17;
  public int JJTADDMNSOP = 18;
  public int JJTADDMNS = 19;
  public int JJTMULDIVOP = 20;
  public int JJTMULDIV = 21;
  public int JJTMODPOWOP = 22;
  public int JJTMODPOW = 23;
  public int JJTEXPRESSION = 24;
  public int JJTLIST = 25;
  public int JJTHASH = 26;
  public int JJTLISTHASHFACTOR = 27;
  public int JJTIDENTIFIER = 28;
  public int JJTBOOLEAN = 29;
  public int JJTFLOAT = 30;
  public int JJTSTRING = 31;
  public int JJTCOLOR = 32;


  public String[] jjtNodeName = {
    "Program",
    "Command",
    "Args",
    "Call",
    "IfStatement",
    "LoopStatement",
    "WhileStatement",
    "ForStatement",
    "Block",
    "Break",
    "Next",
    "Assingment",
    "Operation",
    "OrOp",
    "AndOp",
    "NotOp",
    "CompOp",
    "Comp",
    "AddMnsOp",
    "AddMns",
    "MulDivOp",
    "MulDiv",
    "ModPowOp",
    "ModPow",
    "Expression",
    "List",
    "Hash",
    "ListHashFactor",
    "Identifier",
    "Boolean",
    "Float",
    "String",
    "Color",
  };
}
/* JavaCC - OriginalChecksum=441da9164ef2f05b9b099d1554faeacc (do not edit this line) */
