/* Generated By:JavaCC: Do not edit this line. BegicParserTreeConstants.java Version 6.0_1 */
package jp.tolz.begic.prototype.interpreter.parser;

public interface BegicParserTreeConstants
{
  public int JJTDOPARSE = 0;


  public String[] jjtNodeName = {
    "doParse",
  };
}
/* JavaCC - OriginalChecksum=6eef6e1d979981201d0c68db3451b41a (do not edit this line) */
