/* Generated By:JavaCC: Do not edit this line. BegicParserVisitor.java Version 6.0_1 */
package jp.tolz.begic.prototype.interpreter.parser;

public interface BegicParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTCommand node, Object data);
  public Object visit(ASTArgs node, Object data);
  public Object visit(ASTCall node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTLoopStatement node, Object data);
  public Object visit(ASTWhileStatement node, Object data);
  public Object visit(ASTForStatement node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTBreak node, Object data);
  public Object visit(ASTNext node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTConstantAssignment node, Object data);
  public Object visit(ASTExchange node, Object data);
  public Object visit(ASTOperation node, Object data);
  public Object visit(ASTOrOp node, Object data);
  public Object visit(ASTAndOp node, Object data);
  public Object visit(ASTNotOp node, Object data);
  public Object visit(ASTNot node, Object data);
  public Object visit(ASTCompOp node, Object data);
  public Object visit(ASTComp node, Object data);
  public Object visit(ASTAddMnsOp node, Object data);
  public Object visit(ASTAddMns node, Object data);
  public Object visit(ASTMulDivOp node, Object data);
  public Object visit(ASTMulDiv node, Object data);
  public Object visit(ASTModPowOp node, Object data);
  public Object visit(ASTModPow node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTList node, Object data);
  public Object visit(ASTHash node, Object data);
  public Object visit(ASTListHashFactor node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTBoolean node, Object data);
  public Object visit(ASTFloat node, Object data);
  public Object visit(ASTString node, Object data);
  public Object visit(ASTColor node, Object data);
}
/* JavaCC - OriginalChecksum=ca549b5723c0576625365f572c48bab8 (do not edit this line) */
