/* Generated By:JavaCC: Do not edit this line. BegicParserDefaultVisitor.java Version 6.0_1 */
package jp.tolz.begic.prototype.interpreter.parser;

public class BegicParserDefaultVisitor implements BegicParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTterm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTexpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTinteger node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=fee0a19d6da420cf65cc2ea4f2792b2e (do not edit this line) */
