/* Generated By:JavaCC: Do not edit this line. BegicParserVisitor.java Version 6.0_1 */
package jp.tolz.begic.prototype.interpreter.parser;

public interface BegicParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
}
/* JavaCC - OriginalChecksum=53e7c2bf81face3b9e63312133d4732e (do not edit this line) */
