/* Generated By:JavaCC: Do not edit this line. BegicParserTreeConstants.java Version 6.0_1 */
package jp.tolz.begic.prototype.interpreter.parser;

public interface BegicParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCOMMAND = 1;
  public int JJTARGS = 2;
  public int JJTIFSTATEMENT = 3;
  public int JJTLOOPSTATEMENT = 4;
  public int JJTWHILESTATEMENT = 5;
  public int JJTFORSTATEMENT = 6;
  public int JJTBLOCK = 7;
  public int JJTASSINGMENT = 8;
  public int JJTOPERATION = 9;
  public int JJTOROP = 10;
  public int JJTANDOP = 11;
  public int JJTNOTOP = 12;
  public int JJTCOMPOP = 13;
  public int JJTCOMP = 14;
  public int JJTADDMNSOP = 15;
  public int JJTADDMNS = 16;
  public int JJTMULDIVOP = 17;
  public int JJTMULDIV = 18;
  public int JJTMODPOWOP = 19;
  public int JJTMODPOW = 20;
  public int JJTEXPRESSION = 21;
  public int JJTLIST = 22;
  public int JJTHASH = 23;
  public int JJTLISTHASHFACTOR = 24;
  public int JJTIDENTIFIER = 25;
  public int JJTBOOLEAN = 26;
  public int JJTFLOAT = 27;
  public int JJTSTRING = 28;
  public int JJTCOLOR = 29;


  public String[] jjtNodeName = {
    "Program",
    "Command",
    "Args",
    "IfStatement",
    "LoopStatement",
    "WhileStatement",
    "ForStatement",
    "Block",
    "Assingment",
    "Operation",
    "OrOp",
    "AndOp",
    "NotOp",
    "CompOp",
    "Comp",
    "AddMnsOp",
    "AddMns",
    "MulDivOp",
    "MulDiv",
    "ModPowOp",
    "ModPow",
    "Expression",
    "List",
    "Hash",
    "ListHashFactor",
    "Identifier",
    "Boolean",
    "Float",
    "String",
    "Color",
  };
}
/* JavaCC - OriginalChecksum=f22d081bcdf1a3e338c4f84079dcbe49 (do not edit this line) */
